const sizes=[6,7,8,9,10,11,12,13], colors=['Nero','Argento','Oro'];
const initial={6:{Nero:1,Argento:1,Oro:1},7:{Nero:2,Argento:1,Oro:1},8:{Nero:2,Argento:1,Oro:1},9:{Nero:3,Argento:1,Oro:1},10:{Nero:6,Argento:1,Oro:0},11:{Nero:6,Argento:1,Oro:0},12:{Nero:3,Argento:0,Oro:0},13:{Nero:2,Argento:0,Oro:0}};
let db=JSON.parse(localStorage.getItem('effeRingDB')||'null')||{stock:initial,orders:[],nextId:1};let stockFilter='Nero';
function save(){localStorage.setItem('effeRingDB',JSON.stringify(db));render()}
function fillSelects(){['size','loadSize'].forEach(id=>{let s=document.getElementById(id);s.innerHTML=sizes.map(x=>`<option>${x}</option>`).join('')})}
function soldFor(size,color){return db.orders.filter(o=>o.size==size&&o.color==color).reduce((a,o)=>a+Number(o.qty),0)}
function available(size,color){return (db.stock[size]?.[color]||0)-soldFor(size,color)}
function render(){let total=0,sold=0,inc=0;for(const sz of sizes)for(const c of colors)total+=available(sz,c);db.orders.forEach(o=>{sold+=Number(o.qty);inc+=Number(o.qty)*Number(o.price)});sStock.textContent=total;sSold.textContent=sold;sMonth.textContent='€'+inc.toLocaleString('it-IT');sValue.textContent='€'+(total*79).toLocaleString('it-IT');updateAvailability();renderStock();renderOrders();renderAlerts()}
function updateAvailability(){let sz=size.value,c=color.value;availability.textContent=`Disponibilità: ${available(sz,c)} pezzi`}
function saveOrder(){let c=customer.value.trim(), sz=size.value, col=color.value, q=Number(qty.value), p=Number(price.value);if(!c)return toast('Inserisci il cliente');if(q<1)return toast('Quantità non valida');if(available(sz,col)<q)return toast('Stock insufficiente');db.orders.unshift({id:db.nextId++,date:new Date().toISOString(),customer:c,size:sz,color:col,qty:q,price:p,status:status.value});customer.value='';qty.value=1;save();toast('Ordine creato')}
function renderStock(){stockList.innerHTML=sizes.map(sz=>{let q=available(sz,stockFilter);let cls=stockFilter=='Nero'?'black':stockFilter=='Argento'?'silver':'gold';return `<div class="stock-card"><div><span class="dot ${cls}"></span><b>Taglia ${sz}</b><div class="muted">${stockFilter}</div></div><div class="qty">${q}</div></div>`}).join('')}
function renderAlerts(){let arr=[];for(const sz of sizes)for(const c of colors){let q=available(sz,c);if(q<=1)arr.push(`Taglia ${sz} ${c}: ${q} rimasti`)}alerts.innerHTML=arr.length?arr.map(a=>`<div class="alert">${a}</div>`).join(''):'<p class="muted">Nessun riordino urgente.</p>'}
function renderOrders(){ordersList.innerHTML=db.orders.length?db.orders.slice(0,50).map(o=>`<div class="order"><span class="badge">${o.status}</span><b>#${o.id} ${o.customer}</b><div>Ring ${o.size} ${o.color} × ${o.qty}</div><div class="muted">€${Number(o.qty)*Number(o.price)} · ${new Date(o.date).toLocaleString('it-IT')}</div></div>`).join(''):'<p class="muted">Nessun ordine inserito.</p>'}
function setStockFilter(c,el){stockFilter=c;document.querySelectorAll('.seg button').forEach(b=>b.classList.remove('on'));el.classList.add('on');renderStock()}
function showView(name,el){document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));document.getElementById('view'+name).classList.remove('hidden');document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));el.classList.add('active')}
function loadStock(){let sz=loadSize.value,col=loadColor.value,q=Number(loadQty.value);if(q<1)return toast('Quantità non valida');db.stock[sz][col]=(db.stock[sz][col]||0)+q;save();toast('Stock aggiunto')}
function exportCSV(){let rows=[['ID','Data','Cliente','Taglia','Colore','Quantità','Prezzo','Totale','Stato'],...db.orders.map(o=>[o.id,o.date,o.customer,o.size,o.color,o.qty,o.price,Number(o.qty)*Number(o.price),o.status])];download('effe-ring-ordini.csv',rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(';')).join('\n'),'text/csv')}
function shareBackup(){download('effe-ring-backup.json',JSON.stringify(db,null,2),'application/json')}
function download(name,content,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function importBackupPrompt(){let txt=prompt('Incolla qui il contenuto del backup JSON');if(!txt)return;try{let x=JSON.parse(txt);if(!x.stock||!x.orders)throw Error();db=x;save();toast('Backup importato')}catch(e){toast('Backup non valido')}}
function resetData(){if(confirm('Vuoi davvero cancellare ordini e ripristinare lo stock iniziale?')){db={stock:initial,orders:[],nextId:1};save();toast('Dati resettati')}}
function toast(msg){let t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
[size,color].forEach(el=>el.addEventListener('change',updateAvailability));qty.addEventListener('input',updateAvailability);fillSelects();render();if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js');
